[project]
name = "todo-cli"
version = "0.1.0"
description = "A simple CLI todo list application"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "click>=8.2.0",
]

[tool.uv]
package = true

[project.scripts]
todo-cli = "todo_cli.main:cli"

